name: Google git action
on: 
 push:
  branches:
   - Cypress
   

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci
      - name: Run Cypress Test
        run: npx cypress run --spec "cypress/e2e/googleGitActions/google.cy.js
      
      - uses: actions/upload-artifact@v3                  
        with:            
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore